### PR TITLE
Allow subscribing to multiple topics

### PR DESCRIPTION
**Pull request by corot**
Following navigation issue https://github.com/ros-planning/navigation/issues/69, I have modified the catkinize branch to subscribe to a list of topics, optionally under a common namespace.

I have added simple_costmap_configuration/params/sonar.yaml as an (untested) configuration example

### CODE REVIEW

**Comment by corot** [comment]
Btw, I assume that, in the case you have an array of range sensors, you must publish each one in its own topic. It works also publishing everything in one topic, but visualization with rostopic or RViz sucks. Which approach do you prefer?

**Comment by corot** [comment]
Aggg... I have detected a problem: if sonar_layer subscribes to many topics (11) , isCurrent method often answers "false", as every incoming sensor_msgs/Range sets current_ to false. As a workaround I have commented the current_ = false, but of course I need a better fix. What about having a timeout and a expected_update_rate, as obstacle_layer?

**Comment by DLu** [comment]
Hey - I apologize for the delay here. 

In my personal use, I only used one topic but each sonar sensor had its own /tf frame. Not sure what the general usage is. 

Timeout could work. The current_ logic is probably overly simple.

**Comment by corot** [comment]
Ok, I added a simple timeout mechanism through the "no_readings_timeout" parameter. Btw, are parameters for this layer documented somewhere? I would like to add a note about this new one.

**Comment by DLu** [comment]
Fixed in #6.

**Pull request closed without merging**
