### PR TITLE
Install missing bits in SonarLayer (the costmap plugin + the library (!) )

### PR DESCRIPTION
**Pull request by severin-lemaignan**

### CODE REVIEW

**Comment by DLu** [comment]
Dumb question. What other range sensors are there?

**Comment by severin-lemaignan** [comment]
Infrared sensors! :-)

**Comment by trainman419** [comment]
:+1: 
:shipit:

**Comment by severin-lemaignan** [comment]
@DLu Any reason not to merge this PR?

**Comment by DLu** [comment]
Been on vacation and catching up. Will get to it soon. Sorry for the delay.

**Pull request merged**
