### PR TITLE
RFC: catkinization and updates

### PR DESCRIPTION
**Pull request by trainman419**
I've catkinized the sonar_layer because I'm a catkin fanboy. I can catkinize the rest if you'd like, or pull those commits out of my PR if you're prefer to stick with rosbuild.

More interestingly, I'm interested in using the sonar layer as a local costmap layer on my robot, in conjunction with a laser scanner and an obstacle layer. I have three front-facing sonars that overlap my laser, and two rear-facing sonars that don't.

I've updated the sonar layer so that it works as a local costmap layer (taking into account the robot's position), and I've updated the sonar model so that it takes into account the angle that the sonar is mounted at.

When using the sonar layer by itself, it produces a reasonable map and accumulates free and obstacle probabilities in a reasonable way.

When I start trying to combine the sonar layer with a regular obstacle layer using lidar data, things start getting weird. It looks like the unknown space in the sonar layer are overriding free/raytraced space in the obstacle layer. I'm not sure I understand the new costmap structure well enough to proceed on this. Are all of the layers operating on the same costmap, or do they each maintain their own costmap internally, with the merging handled elsewhere? (If this is documented elsewhere, feel free to link to me to manual and tell me to RTFM).

General thoughts?

### CODE REVIEW

**Comment by DLu** [comment]
What order are you using the layers? Both the sonar layer and the obstacle layer keep their own costmap that get aggregated into the master costmap (which is the one that is published and planned upon). The aggregation step for the sonar layer uses [updateWithMax](https://github.com/ros-planning/navigation/blob/hydro-devel/costmap_2d/src/costmap_layer.cpp#L21) which _should_ handle the unknown, but I haven't thoroughly tested it.

**Comment by trainman419** [comment]
This shows the issue fairly well. I see the same behavior regardless of the ordering of the sonar and obstacle layers.

With the obstacle layer enabled and the sonar layer disabled:
sonar_off

With both layers enabled, the state of the world is significantly less known:
sonar_on

**Comment by DLu** [comment]
Just to be clear, what is the order of the plugins?

**Comment by trainman419** [comment]
I have the sonar layer listed first, followed by the obstacle layer and the footprint layer. The remaining plugins are disabled.

I played with this a bit, and it looks like the sonar layer is setting it's default value to [`to_cost(0.5)`](https://github.com/DLu/navigation_layers/blob/master/sonar_layer/src/sonar_layer.cpp#L17) rather than `NO_INFORMATION`. When I switch the default cost to `NO_INFORMATION`, I get a behavior closer to what I expect.

**Comment by DLu** [comment]
Ah right. I have not quite finished the layer. The problem is that the values in the sonar layer are probabilities, and should be written into the master layer as costs. I can make an update for this.

**Comment by DLu** [comment]
I have made some new updates that incorporate your changes, along with a brand new catkinize branch for you. Thanks for your contributions. Let me know if the new changes act better.

**Pull request closed without merging**
