### PR TITLE
Implement Layer class reset method so clear costmaps service also works

### PR DESCRIPTION
**Pull request by corot**
on range sensor layers

### CODE REVIEW

**Comment by corot** [comment]
I also wanted to make clear costmaps recovery behavior to work here. Does it make sense to do so?
This layer doesn't appear in the list of clearable layers (what actually I don't know where it comes from!)

**Comment by DLu** [comment]
The clear costmaps recovery behavior already works, since it implements the CostmapLayer functionality. To make it appear on the list of clearable layers, set the parameter /move_base_node/RECOVERY_BEHAVIOR_NAMESPACE/layer_names to the name of your RangeSensorLayer. 

When called, this will set all values in the range to NO_INFORMATION. 

Is there another reason for including the reset method? Or shall I close the PR?

**Comment by corot** [comment]
Thanks for the information; I was fully ignorant of that configuration!

Yes, I think "reset" is still required for "/move_base/clear_costmaps" service to work.

**Comment by corot** [comment]
I have tried what you said and something funny happen: the whole layer becomes an obstacle! ([picture](https://www.dropbox.com/s/meex9ta1750h6hy/snapshot2.png?dl=0)). So I suppose that NO_INFORMATION value is considered as an obstacle? Doesn't look like very practical!

**Comment by DLu** [comment]
That doesn't seem correct. What layers are you using?

**Comment by corot** [comment]
Typical configuration plus your range sensor layer. But the one that fills all as obstacles is range sensor, because it becomes clean again when I disable it.

https://github.com/corot/thorp/blob/master/thorp_bringup/param/move_base/local_costmap_params.yaml
https://github.com/corot/thorp/blob/master/thorp_bringup/param/move_base/move_base_params.yaml

**Comment by corot** [comment]
I think I found the problem. When using clear costmap recovery behaviors, cells are set as NO_INFORMATION, and then updateCosts considers that as lethal obstacle.

@DLu, I extended the PR with the reset method. Tell me if you prefer two separated PRs.

**Comment by DLu** [comment]
Would you mind starting a fresh pull request with just f3e3cdb included? I'm not convinced that we need the earlier part.

**Comment by corot** [comment]
Done: https://github.com/DLu/navigation_layers/pull/24

The other change is required to make clear_costmaps move_base's service clear also this layer. It is implemented as in obstacle layer, and it works, so... what are you uneasy with? :grin:

**Comment by DLu** [comment]
Ok, after further review, you are correct. I'm not sure what code I was looking at before, but I thought CostmapLayer overrode the reset method. It doesn't, so your code is necessary. I'll merge here.

**Pull request merged**
